### ISSUE TITLE
Link at top of Github Repository home page is dead

### ISSUE THREAD

**Issue by amurph491** [bloomberg/foml#6]
It currently points at `https://www.techatbloomberg.com/foml` , should probably be `https://bloomberg.github.io/foml`
![foml-gh](https://user-images.githubusercontent.com/1483361/50291696-480f7700-043d-11e9-9c3c-30357f13b436.PNG)

**Comment by kpfleming** [comment]
Thanks for the report, we'll get this corrected.

**Comment by kpfleming** [comment]
The link is now functional again.
